### ISSUE TITLE
案出しと絞込みを行いました

### ISSUE THREAD

**Issue by g2116034** [enpit2016fun/pbl_f#1]
・子ども、若者、大人、高齢者ごとに分け、ブレインストーミングで案だし
↓
・N3法を用いて案の絞込み
↓
案の具体的な内容を各自考える(未完了)

**Comment by TakahiroTsujiura** [comment]
「案の具体的な内容を各自考える」は以下に別のissueを作りました
https://github.com/enpit2016fun/pbl_f/issues/4
