### ISSUE TITLE
テンプレを発見し、なぜ単純で簡易版だと思ったのか？の理由を見つける

### ISSUE THREAD

**Issue by g2116034** [enpit2016fun/pbl_f#9]

**Comment by TakahiroTsujiura** [comment]
・欲しい理由がない
・買った側がどんなメリットを受けられるのかがない
・なぜならの部分が説得力に欠ける
・一つ一つが短文過ぎて後はプレゼン能力に依存する
・DVDプレゼンみたいにストーリーがあったらいいのかもしれない
・構成が悪いって感じ
・「○○という解決策を見つけました！」とか口頭で言うのはいいけど普通資料に直接書かないよね
・ストーリーがないに関係するかもしれないけど背景がない
